OpenDolphin
===========

Welcome to the OpenDolphin documentation

.The documentation comes in two parts
The User Guide::
    explains the architecture, the concepts, and possible usages.
    It is like a book that you may want to read to understand what OpenDolphin
    is all about, what drives its design, and how it works in general.

The API Reference::
    lets you quickly look up code snippets that you need when using OpenDolphin in your
    own projects. It is all about the implementation details.

The user guide and the references are cross-linked such that you can always jump back and forth
between the overall picture and how it materializes in the details.
No matter where you start, you can always refer from detailed explanations to its place in the
architecture and vice versa.


[quote, Johann Wolfgang v. Goethe, Farbenlehre]
____
Understanding means recognizing the details in the whole and the whole from its details.
____


== User Guide

OpenDolphin is a Model-View-Controller architecture that enforces strict decoupling between
Views and Controllers. They can never refer directly to each other. Their sole mean of communication
is through shared _Presentation Models_.

The separation enables the use of remoting between Views and Controllers. They can run on different machines while
OpenDolphin cares for synchronizing the Presentation Models between them.

.OpenDolphin introduces remoting between Views and Controllers by means of shared Presentation Models
[ditaa]
----
      Client                                           Server
 /--------------\                                 /--------------\
 |              |                                 |              |
 |     View     |                                 |  Controller  |
 |              |                                 |              |
 |   /-------------------+               +-------------------\   |
 |   |                   |  OpenDolphin  |                   |   |
 \---| PresentationModel |<------------->| PresentationModel |---/
     |                   |               |                   |
     \-------------------+               +-------------------/
----

The net effect is that Controllers - which embody the _application logic_ - can live in a
Java Enterprise environment while the Views can display the user interface with all the
capabilities of a local device, be it in the browser or through native Desktop technologies.

Because they live in the enterprise environment, controllers have direct, efficient access
to all enterprise resources. They are themselves an important resource since they control
*what* is displayed to the user by providing the respective Presentation Models.

Views live on the client device and determine *how* to display Presentation Models
to the user. To that end, they can leverage the full range of their device features.




== API Reference

=== Server Side (Controller)

==== Registering Actions
==== Creating Presentation Models
==== Reading and Writing Attribute Values
==== Binding to Attributes

=== Client Side (View)

==== Java Desktop (Swing, JavaFX, and others)

===== Creating Presentation Models
===== Reading and Writing Attribute Values
===== Binding to Attributes
===== Sending Commands

==== Browser (JavaScript, TypeScript, and others)
===== Creating Presentation Models
===== Reading and Writing Attribute Values
===== Binding to Attributes
===== Sending Commands