Attributes contains unique Id and unique property name per presentation model.

A client side ClientAttribute is considered a remote representation of a ServerAttribute.

But it's possible to create attributes that exist only in the client side as per presentation models.

To create a new clientAttribute in java the preferred constructor

[NOTE]
====
 ClientAttribute(String propertyName, Object initialValue, String qualifier = null, Tag tag = Tag.VALUE)
====

A java example
[source,java]
----
 ClientAttribute firstNameAttr = new ClientAttribute(ATT_FIRSTNAME, "", null, null);
----

To create a new clientAttribute in web the constructor
[NOTE]
====
 ClientAttribute(propertyName, qualifier, value, tag)
====

A javascript example
[source,html]
----
var firstNameAttr = clientDolphin.attribute(ATT_FIRSTNAME, null, "Initial Value");
----


.OpenDolphin attributes tags
|===
|Tag |Description

|Tag.VALUE
|The actual value of the attribute. This is the default if no tag is given.

|Tag.LABEL
|The to-be-displayed String, not the key. Internationalization happens on the server.

|Tag.WIDGET_HINT
|A single text; e.g. "textArea" if the String value should be displayed in a text area instead of a textField

|Tag.VALUE_TYPE
|A single text; e.g. "java.util.Date" if the value String represents a date

|Tag.REGEX
|Regular expression for local, syntactical constraints like in "rejectField"

|Tag.HELP_URL
|Url.toExternalForm()

|Tag.TOOLTIP
|Tooltip text for the attribute

|Tag.MANDATORY
|"true" or "false"; maps to Grails constraint nullable:false

|Tag.VISIBLE
|"true" or "false"; maps to Grails constraint display:true

|Tag.ENABLED
|"true" or "false"
|===



